import { defaultSchema } from "rehype-sanitize";

// markdown 中允许解析的 html 标签配置
export const allowSchema = {
  ...defaultSchema,
  tagNames: [
    "br",
    "p",
    "u",
    "em",
    "strong",
    "code",
    "span",
    "table",
    "thead",
    "tbody",
    "tr",
    "th",
    "td",
    "caption",
    "colgroup",
    "col",
    // 仅允许上面这些 html 标签, 包括表格
    "annotation",
    "math",
    "menclose",
    "mfrac",
    "mglyph",
    "mi",
    "mlongdiv",
    "mmultiscripts",
    "mn",
    "mo",
    "mover",
    "mpadded",
    "mphantom",
    "mroot",
    "mrow",
    "ms",
    "mscarries",
    "mscarry",
    "msgroup",
    "msline",
    "mspace",
    "msqrt",
    "msrow",
    "mstack",
    "mstyle",
    "msub",
    "msubsup",
    "msup",
    "mtable",
    "mtd",
    "mtext",
    "mtr",
    "munder",
    "munderover",
    "semantics",
    // 允许上面这些 MathML 标签
  ],
  attributes: {
    ...defaultSchema.attributes,
    "*": ["className", "style"], // 允许公式使用的样式类
    table: ["class", "style", "border", "cellpadding", "cellspacing"],
    th: ["class", "style", "align", "colspan", "rowspan"],
    td: ["class", "style", "align", "colspan", "rowspan"],
    tr: ["class", "style"],
    thead: ["class", "style"],
    tbody: ["class", "style"],
  },
};
